# -*- coding: utf-8 -*-
"""Modul 5 202110370311503

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuZiEt4Is3oUjpWOkq0iu_f_EL7DixSM
"""

#latihan 1
import matplotlib.pyplot as plt
import numpy as np

xpointsbaru= np.array([1,4])
ypointsbaru= np.array([2,4])

plt.plot(xpointsbaru,ypointsbaru)
plt.legend("b")
plt.title("Percobaan 1")
plt.show()

#latihan 2
import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([1, 8, 10])
ypoints = np.array([3, 10, 5])

plt.figure(figsize=(5, 5))
plt.legend(loc="upper left")
plt.title("Percobaan 2")
plt.xlabel("This is Label Exis X")
plt.ylabel("This is Label Exis Y")
plt.plot(xpoints, ypoints, marker="*", color="green", ls="dotted", linewidth="2.5")

plt.xlim([0, 16])
plt.ylim([0, 16])
plt.show()

#latihan 3
import matplotlib.pyplot as plt
import numpy as np

y1 = np.array([3, 8, 1, 10])
y2 = np.array([6, 2, 7, 11])
y3 = np.array([4, 2, 4, 12])

plt.plot(y1, label="Grafik 1", marker="H", color="green", ls="dashed")
plt.plot(y2, label="Grafik 2", color="yellow")
plt.plot(y3, label="Grafik 3", marker="*", ls="dotted", color="purple")

plt.title('Percobaan 3')
plt.xlabel('Nilai x')
plt.ylabel('Nilai y')

plt.legend()
plt.show()

#latihan 4
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [3, 7, 2, 8, 5]

plt.scatter(x, y, label="sX", marker="x", color="purple")
plt.title("Percobaan 4")

plt.show()

#latihan 5
from matplotlib import pyplot as plt
from numpy.random import normal
from numpy import mean, std
from scipy.stats import norm


sample = normal(loc=50, scale=5, size=1000)
plt.hist(sample, bins=10)
plt.title("Percobaan 5")
plt.show()

sample_mean = mean(sample)
sample_std = std(sample)
print("Mean=%.3f \nStandard Deviation=%.3f" % (sample_mean, sample_std))

dist = norm(sample_mean, sample_std)
dist

values = [value for value in range(30, 70)]
probabilitas = [dist.pdf(value) for value in values]
probabilitas

plt.hist(sample, bins=10, density=True)
plt.plot(values, probabilitas)
plt.show()
